language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO=2.2.9
  - DJANGO=3.0.1

jobs:
  exclude:
    - python: 3.5
      env: DJANGO=3.0.1
    - python: 3.8
      env: DJANGO=2.2.9

install:
  - pip install -q django==$DJANGO pytz
  - pip install coveralls

script:
    coverage run --source=unixtimestampfield setup.py test

after_success:
  coveralls

notifications:
  email:
    recipients:
      - ymy1019@gmail.com
