language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.7
  - 3.8

env:
  - DJANGO='django>=2.2.9'

install:
  - pip install -q $DJANGO pytz
  - pip install six
  - pip install coveralls

script:
    coverage run --source=unixtimestampfield setup.py test

after_success:
  coveralls

notifications:
  email:
    recipients:
      - ymy1019@gmail.com
